# Debug Mode
debug: false

# Whether to use permissions or the list below to check if a player is able to execute commands
# Types: LIST, PERMISSION
permissionType: 'PERMISSION'

# List of admins that can use the plugins commands (Only works if permissionType is set to LIST)
admins:
  - 'UnlimitedNinjas'