name: Atom
description: In-game File Editor

main: tsp.atom.Atom
version: 1.2
author: Silent

commands:
  atom:
    usage: /atom
    description: Plugin Information
  editor:
    usage: /editor [file]
    description: Open the editor for given file
  viewfile:
    usage: /viewfile <file>
    description: View a files contents
    aliases: [vf]
  editfile:
    usage: /editfile <line> f:<file> t:<text>
    description: Edit a files line
    aliases: [ef]
  viewdir:
    usage: /viewdir <path>
    description: View contents of a directory
    aliases: [vd, viewdirectory]
  deletefile:
    usage: /deletefile <file>
    description: Delete a file
    aliases: [df]

permissions:
  atom.admin:
    default: op