name: ${project.name}
description: ${project.description}

main: tsp.atom.Atom
version: ${project.version}
author: Silent
api-version: 1.13

commands:
  atom:
    usage: /atom
    description: Plugin Information
  editor:
    usage: /editor [file]
    description: Open the editor for given file
  viewfile:
    usage: /viewfile <file>
    description: View a files contents
    aliases: [vf]
  editfile:
    usage: /editfile <line> f:<file> t:<text>
    description: Edit a files line
    aliases: [ef]
  viewdir:
    usage: /viewdir <path>
    description: View contents of a directory
    aliases: [vd, viewdirectory]
  deletefile:
    usage: /deletefile <file>
    description: Delete a file
    aliases: [df]

permissions:
  atom.admin:
    default: op
  atom.command.editor:
    default: op
  atom.command.viewfile:
    default: op
  atom.command.editfile:
    default: op
  atom.command.viewdir:
    default: op
  atom.command.deletefile:
    default: op